services:
    app:
        image: node:16-alpine
        command: sh -c "npm install && npm run dev"
        ports:
                - 8090:8090
        working_dir: /api-irrigate
        volumes:
                - ./:/api-irrigate